const { Pool } = require("pg");
const { getEnv } = require("../config/env");

const { databaseUrl } = getEnv();

const pool = new Pool({
  connectionString: databaseUrl,
  ssl: { rejectUnauthorized: false },
  max: 1,
  idleTimeoutMillis: 0,
  connectionTimeoutMillis: 10000,
});

pool.on("error", (err) => {
  console.error("DB pool error:", err.message);
});

const initDB = async () => {
  if (!databaseUrl) {
    throw new Error("SUPABASE_DB_URL is not set. Cannot connect to database.");
  }

  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS members (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'admin',
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS news (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        excerpt TEXT,
        content TEXT,
        category TEXT NOT NULL DEFAULT 'General',
        badge_text TEXT,
        badge_color TEXT NOT NULL DEFAULT '#2D7D6F',
        image_url TEXT,
        published BOOLEAN NOT NULL DEFAULT TRUE,
        created_by BIGINT REFERENCES members(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        event_date DATE NOT NULL,
        event_time TEXT,
        location TEXT,
        image_url TEXT,
        category TEXT,
        is_featured BOOLEAN NOT NULL DEFAULT FALSE,
        published BOOLEAN NOT NULL DEFAULT TRUE,
        created_by BIGINT REFERENCES members(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS programs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        duration TEXT,
        icon TEXT,
        color TEXT NOT NULL DEFAULT '#2D7D6F',
        features TEXT[] NOT NULL DEFAULT '{}',
        normal_fee TEXT,
        addon_fee TEXT,
        addon_courses TEXT[] NOT NULL DEFAULT '{}',
        seats INTEGER,
        tags TEXT[] NOT NULL DEFAULT '{}',
        published BOOLEAN NOT NULL DEFAULT TRUE,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_by BIGINT REFERENCES members(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  image_url TEXT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'image',
  category TEXT NOT NULL DEFAULT 'Campus Life',
  published BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by BIGINT REFERENCES members(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Backfill for existing databases created before media_type existed
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT 'image';

      CREATE TABLE IF NOT EXISTS testimonials (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        role TEXT,
        content TEXT NOT NULL,
        rating INTEGER NOT NULL DEFAULT 5,
        avatar_url TEXT,
        video_url TEXT,
        thumbnail_url TEXT,
        published BOOLEAN NOT NULL DEFAULT TRUE,
        created_by BIGINT REFERENCES members(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS resources (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        category TEXT NOT NULL DEFAULT 'General',
        subject TEXT,
        year TEXT,
        file_url TEXT NOT NULL,
        file_name TEXT,
        file_size TEXT,
        file_type TEXT,
        published BOOLEAN NOT NULL DEFAULT TRUE,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_by BIGINT REFERENCES members(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );  
    `);
    console.log("Database schema initialized");
  } finally {
    client.release();
  }
};

module.exports = { pool, initDB };
